load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "solution",
    srcs = ["solution.cpp", "solution.h", "helpers.h"],
    visibility = ["//visibility:public"],
    copts = ["-std=c++17"]
)