name: "\U0001F31F New article addition"
description: Submit a proposal/request to implement a new article
labels: [ "New article" ]

body:
  - type: textarea
    id: description-request
    validations:
      required: true
    attributes:
      label: Article description
      description: |
        Put any and all important information relative to the article
      value: |
        Description of the article (such as Stack in C++, Queue in Typescript)
        **References**
        * Reference 1
        * Reference 2
  - type: dropdown
    id: article-topics
    validations:
      required: true
    attributes:
      label: Topic 
      description: |
        Select one or more topics for the article
      multiple: true
      options:
        - label: Big-O
        - label: Array
        - label: Linked List
        - label: Stack
        - label: Queue
        - label: Set
        - label: Graph - Graph Representation
        - label: Graph Traversal - Depth First Search
        - label: Graph Shortest Paths - Dijkstra's Algorithm
  - type: dropdown
    id: article-program-language
    validations:
      required: true
    attributes:
      label: Select a program language
      options:
        - C (c)
        - C++ (cpp)
        - Java (java)
        - Python (py)
        - Rust (rs)
        - Typescript (ts)

## Article Checklist 

- [ ] ℹ️ Definition
- [ ] 🎨 Design
- [ ] 💻 Implementation
- [ ] 📈 Complexity Analysis
- [ ] 🔗 Further Reading