name: "\U0001F31F New article addition"
description: Submit a proposal/request to implement a new article
labels: [ "New article" ]

body:
  - type: textarea
    id: description-request
    validations:
      required: true
    attributes:
      label: Article description
      description: |
        Put any and all important information relative to the article
      value: |
        Description of the article (such as Stack in C++, Queue in Typescript)
        
        **References**
        
        * Reference 1
        * Reference 2
  - type: dropdown
    id: article-topics
    validations:
      required: true
    attributes:
      label: Topic 
      description: Select one or more topics for the article
      multiple: true
      options:
        - Big-O
        - Array
        - Linked List
        - Stack
        - Queue
        - Set
        - Tree
        - Graph - Graph Representation
        - Graph Traversal - Depth First Search
        - Graph Shortest Paths - Dijkstra's Algorithm
  - type: dropdown
    id: article-program-language
    validations:
      required: true
    attributes:
      label: Programming language
      description: Select a programming language for the article
      options:
        - C (c)
        - C++ (cpp)
        - Java (java)
        - Python (py)
        - Rust (rs)
        - Typescript (ts)
  - type: checkboxes
    id: article-checklist
    validations:
      required: false
    attributes:
      label: Article Checklist
      options:
        - label: ℹ️ Definition
        - label: 🎨 Design
        - label: 💻 Implementation
        - label: 📈 Complexity Analysis
        - label: 🔗 Further Reading
        - label: 🏁 Update README
