load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "solutionA",
    srcs = ["solutionA.cpp"],
    visibility = ["//visibility:public"]
)

cc_binary(
    name = "solutionB",
    srcs = ["solutionB.cpp"],
    visibility = ["//visibility:public"]
)