load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "solution1",
    srcs = ["solution1.cpp", "helpers.h"],
    visibility = ["//visibility:public"]
)

cc_binary(
    name = "solution2",
    srcs = ["solution2.cpp", "helpers.h"],
    visibility = ["//visibility:public"]
)